### PR TITLE
CP-20761: Rename clashing modules

### PR DESCRIPTION
**Pull request by gaborigloi**
As a preparation for the ppx branch merge, we'd like to get as many of the ppx changes into trunk as possible, to minimize the difference between the two branches when it comes to merging.

However, the proper way to fix this issue would be to move to the upstream Result module, to remove the duplicated code - this is the smallest change that makes it compile in the `experimental/ppx` branch. I have already done this here: <https://github.com/gaborigloi/gpumon/tree/remove_result>, so maybe we should merge that into `ppx_trunk` instead, but I don't have permission to create the branch here.

### CODE REVIEW

**Comment by jonludlam** [comment]
I vote for removing the duplicate result module and just rely on the real one. We've done the minimal in other repos for expediency, but it's time for the proper fixes now :-)

**Comment by gaborigloi** [comment]
@jonludlam Sounds good, I'll try to do that then, and send a new PR :-)
We will have to update the SPEC file of gpumon as well, to point to the new branch, which removes this custom Result module.

**Comment by gaborigloi** [comment]
@jonludlam actually, to use the upstream Result type or the Rresult combinator library, I think we would need a package for these, as trunk does not use `xs-opam-repo` :-/
So we have two options:
1. Merge this quick fix into trunk
2. Properly remove the duplicate Result module, and merge it later with the other ppx changes

**Comment by jonludlam** [comment]
Ah, sorry, I hadn't spotted that this was a PR for trunk, not for a ppx_trunk branch. As you were then, reopen this and we'll fix the problem properly in ppx_trunk.

**Comment by gaborigloi** [comment]
@jonludlam Oh ok, but I've already ported it to the `Rresult` library, as I saw that you used the same thing in `ocaml-rpc`: https://github.com/gaborigloi/gpumon/tree/remove_result

**Comment by gaborigloi** [comment]
As these are two different approaches, maybe there is no point in merging this to trunk, if we will remove the Result module anyway when merging the ppx branch?

**Comment by lindig** [comment]
I'm happy to accept the code using `Rresult` library as the cleaner solution long term.

**Comment by lindig** [comment]
Please open a new PR for the alternative solution. I've created a new branch `ppx_trunk` for that.

**Comment by gaborigloi** [comment]
Opened https://github.com/xenserver/gpumon/pull/18, that puts some of these changes on trunk.

**Pull request closed without merging**
